### ISSUE TITLE
A couple of improvements

### ISSUE THREAD

**Issue by ipedrazas** [JacksonZ03/authjs-youtube-tutorial#1]
Awesome tutorial!!!

There are a couple of things that you can do to make it even better:

1. By adding the following volume to your Postgres service, the `postgres-schema.sql` will be executed when the container is initialised. It saves you the issue of having to go to PgAdmin to load the schema :)

```
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres-schema.sql:docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
```

Another thing to be aware of is the postgres extension that you use: "uuid-ossp";`. You should use `gen_random_uuid()` instead (that comes by default in all new Postgres versions).

`gen_random_uuid()` uses the pgcrypto extension, `uuid_generate_v4()` uses the `uuid-ossp` extension (that you have to install). Besides that, `gen_random_uuid` is 4 times faster than `uuid_generate_v4` :)

Your schema file would be like:

```
CREATE TYPE AuthRole AS ENUM ('USER', 'ADMIN');

CREATE TABLE
  users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255),
    email VARCHAR(255),
    "emailVerified" TIMESTAMPTZ,
    image TEXT,
    role AuthRole NOT NULL DEFAULT 'USER',
    PRIMARY KEY (id)
  );

CREATE TABLE
  accounts (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    "userId" uuid NOT NULL,
    type VARCHAR(255) NOT NULL,
    provider VARCHAR(255) NOT NULL,
    "providerAccountId" VARCHAR(255) NOT NULL,
    refresh_token TEXT,
    access_token TEXT,
    expires_at BIGINT,
    id_token TEXT,
    scope TEXT,
    session_state TEXT,
    token_type TEXT,
    PRIMARY KEY (id)
  );

CREATE TABLE
  verification_token (
    identifier TEXT NOT NULL,
    expires TIMESTAMPTZ NOT NULL,
    token TEXT NOT NULL,
    PRIMARY KEY (identifier, token)
  );
```

I didn't want to create a PR because your code matches the one in your video, but I wanted to let you know ways of improving it 🙌
